resource_group_name     = "test-p-myrg"
resource_group_location = "West Europe"
virtual_network_name    = "test-p-myvnet"
subnet_name             = "test-p-mysubnet"
//public_ip_name              = "publicip019"
network_security_group_name = "test-p-mynsg"
network_interface_name      = "test-p-mynic"
windows_virtual_machine_name  = "test-p-mywindowsvm"